# Generated by Django 5.0.2 on 2024-03-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0004_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="expiry_month",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="expiry_year",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
