# Generated by Django 5.0.2 on 2024-03-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0005_alter_payment_expiry_month_alter_payment_expiry_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="cvc",
            field=models.IntegerField(null=True),
        ),
    ]
