# Generated by Django 5.0.2 on 2024-03-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0006_alter_payment_cvc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AlterField(
            model_name="payment",
            name="cvc",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="expiry_month",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="expiry_year",
            field=models.IntegerField(),
        ),
    ]
