# Generated by Django 5.0.2 on 2024-03-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0008_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
