# Generated by Django 5.0.2 on 2024-03-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0010_alter_borrowing_options_payment_amount_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
