# Generated by Django 5.0.2 on 2024-03-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0011_payment_stripe_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
