# Generated by Django 5.0.2 on 2024-03-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0012_alter_payment_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="stripe_payment_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
