# Generated by Django 5.0.2 on 2024-03-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0014_payment_refund"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="refund",
        ),
    ]
