# Generated by Django 5.0.2 on 2024-03-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0015_remove_payment_refund"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded",
            field=models.BooleanField(default=False),
        ),
    ]
