# Generated by Django 5.0.2 on 2024-03-11 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0017_borrowing_fines_payment_fines"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="fines",
            new_name="fines_applied",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="fines_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Fines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.IntegerField()),
                ("expiry_month", models.IntegerField()),
                ("expiry_year", models.IntegerField()),
                ("cvc", models.IntegerField()),
                (
                    "fines_paid",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("stripe_payment_id", models.CharField(max_length=255, null=True)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_fines",
                        to="borrowings.borrowing",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_fines",
                        to="borrowings.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="payment",
            name="fines",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="borrowings.fines",
            ),
        ),
    ]
