# Generated by Django 5.0.2 on 2024-03-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0018_rename_fines_borrowing_fines_applied_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="borrowings",
                to="borrowings.payment",
            ),
        ),
    ]
