# Generated by Django 5.0.2 on 2024-03-11 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0019_borrowing_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fines",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_fines",
                to="borrowings.payment",
            ),
        ),
    ]
