# Generated by Django 5.0.2 on 2024-03-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0020_alter_fines_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fines",
            options={"verbose_name": "fines", "verbose_name_plural": "fines"},
        ),
    ]
